export const errors = {
    "additional-items-error": "Array at `{{pointer}}` may not have an additional item `{{key}}`",
    "additional-properties-error":
        "Additional property `{{property}}` on `{{pointer}}` does not match schema `{{schema}}`",
    "all-of-error": "Value `{{value}}` at `{{pointer}}` does not match schema of `{{allOf}}`",
    "any-of-error": "Value `{{value}}` at `{{pointer}}` does not match any schema of `{{anyOf}}`",
    "const-error": "Expected value at `{{pointer}}` to be `{{expected}}`, but value given is `{{value}}`",
    "contains-any-error": "The array at `{{pointer}}` must contain at least one item",
    "contains-array-error": "The property at `{{pointer}}` must not be an array",
    "contains-error": "The array at `{{pointer}}` must contain an element that matches `{{schema}}`",
    "contains-min-error": "The array at `{{pointer}}` contains {{delta}} too few items matching `{{schema}}`",
    "contains-max-error": "The array at `{{pointer}}` contains {{delta}} too many items matching `{{schema}}`",
    "enum-error": "Expected given value `{{value}}` in `{{pointer}}` to be one of `{{values}}`",
    "exclusive-maximum-error": "Value in `{{pointer}}` is `{{length}}`, but should be at most `{{maximum}}`",
    "exclusive-minimum-error": "Value in `{{pointer}}` is `{{length}}`, but should be at minimum `{{minimum}}`",
    "forbidden-property-error": "Property name `{{property}}` at `{{pointer}}` is not allowed",
    "format-date-error": "Value `{{value}}` at `{{pointer}}` is not a valid date",
    "format-date-time-error": "Value `{{value}}` at `{{pointer}}` is not a valid date-time",
    "format-duration-error": "Value `{{value}}` at `{{pointer}}` is not a valid duration",
    "format-email-error": "Value `{{value}}` at `{{pointer}}` is not a valid email",
    "format-hostname-error": "Value `{{value}}` at `{{pointer}}` is not a valid hostname",
    "format-ipv4-error": "Value `{{value}}` at `{{pointer}}` is not a valid IPv4 address",
    "format-ipv4-leading-zero-error":
        "IPv4 addresses starting with zero are invalid, since they are interpreted as octals",
    "format-ipv6-error": "Value `{{value}}` at `{{pointer}}` is not a valid IPv6 address",
    "format-ipv6-leading-zero-error":
        "IPv6 addresses starting with zero are invalid, since they are interpreted as octals",
    "format-json-pointer-error": "Value `{{value}}` at `{{pointer}}` is not a valid json-pointer",
    "format-regex-error": "Value `{{value}}` at `{{pointer}}` is not a valid regular expression",
    "format-time-error": "Value `{{value}}` at `{{pointer}}` is not a valid time",
    "format-uri-error": "Value `{{value}}` at `{{pointer}}` is not a valid uri",
    "format-uri-reference-error": "Value `{{value}}` at `{{pointer}}` is not a valid uri-reference",
    "format-uri-template-error": "Value `{{value}}` at `{{pointer}}` is not a valid uri-template",
    "format-url-error": "Value `{{value}}` at `{{pointer}}` is not a valid url",
    "format-uuid-error": "Value `{{value}}` at `{{pointer}}` is not a valid uuid",
    "invalid-data-error": "No value may be specified in `{{pointer}}`",
    "invalid-property-name-error": "Invalid property name `{{property}}` at `{{pointer}}`",
    "maximum-error": "Value in `{{pointer}}` is `{{length}}`, but should be `{{maximum}}` at maximum",
    "max-items-error": "Too many items in `{{pointer}}`, should be `{{maximum}}` at most, but got `{{length}}`",
    "max-length-error": "Value `{{pointer}}` should have a maximum length of `{{maxLength}}`, but got `{{length}}`.",
    "max-properties-error":
        "Too many properties in `{{pointer}}`, should be `{{maxProperties}}` at most, but got `{{length}}`",
    "minimum-error": "Value in `{{pointer}}` is `{{length}}`, but should be `{{minimum}}` at minimum",
    "min-items-error": "Too few items in `{{pointer}}`, should be at least `{{minItems}}`, but got `{{length}}`",
    "min-items-one-error": "At least one item is required in `{{pointer}}`",
    "min-length-error": "Value `{{pointer}}` should have a minimum length of `{{minLength}}`, but got `{{length}}`.",
    "min-length-one-error": "A value is required in `{{pointer}}`",
    "missing-one-of-declarator-error": "Missing oneOf declarator `{{declarator}}` in `{{pointer}}`",
    "min-properties-error":
        "Too few properties in `{{pointer}}`, should be at least `{{minProperties}}`, but got `{{length}}`",
    "missing-array-item-error": "Array at '{{pointer}}' has a missing item at '{{key}}'",
    "missing-dependency-error": "The required propery '{{missingProperty}}' in `{{pointer}}` is missing",
    "missing-one-of-property-error": "Value at `{{pointer}}` property: `{{property}}`",
    "multiple-of-error": "Expected `{{value}}` in `{{pointer}}` to be multiple of `{{multipleOf}}`",
    "multiple-one-of-error": "Value `{{value}}` should not match multiple schemas in oneOf `{{matches}}`",
    "no-additional-properties-error": "Additional property `{{property}}` in `{{pointer}}` is not allowed",
    "not-error": "Value `{{value}}` at pointer should not match schema `{{not}}`",
    "one-of-error": "Value `{{value}}` in `{{pointer}}` does not match any given oneof schema",
    "one-of-property-error":
        "Failed finding a matching oneOfProperty schema in `{{pointer}}` where `{{property}}` matches `{{value}}`",
    "pattern-error": "Value in `{{pointer}}` should match `{{description}}`, but received `{{received}}`",
    "pattern-properties-error":
        "Property `{{key}}` does not match any patterns in `{{pointer}}`. Valid patterns are: {{patterns}}",
    "required-property-error": "The required property `{{key}}` is missing at `{{pointer}}`",
    /** return schema-warning with createSchemaWarning:true when a valid, but undefined  property was found */
    "schema-warning": "Failed retrieving a schema from '{{pointer}}' to key '{{key}}'",
    "type-error": "Expected `{{value}}` ({{received}}) in `{{pointer}}` to be of type `{{expected}}`",
    "undefined-value-error": "Value must not be undefined in `{{pointer}}`",
    "unevaluated-property-error": "Invalid unevaluated property `{{pointer}}`",
    "unevaluated-items-error": "Invalid unevaluated item `{{pointer}}`",
    "unique-items-error":
        "Items in array must be unique. Value `{{value}}` in `{{pointer}}` is a duplicate of {{duplicatePointer}}.",
    "unknown-property-error": "Could not find a valid schema for property `{{pointer}}` within object",
    "value-not-empty-error": "A value for `{{property}}` is required at `{{pointer}}`"
};
