name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        name: install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install yarn (required locally)
              run: npm install --global yarn
            - uses: actions/setup-node@v3
              with:
                  node-version: "21"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: unit tests
              run: yarn test:unit:ci
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: unit test results
                  path: test-result-unit.json
                  reporter: mocha-json
            - name: Test spec v4
              run: yarn test:spec:4:ci
            - name: Test spec v6
              run: yarn test:spec:6:ci
            - name: Test spec v7
              run: yarn test:spec:7:ci
            - name: Test spec 2019-09
              run: yarn test:spec:2019:ci
            - name: Archive code coverage results
              uses: actions/upload-artifact@v3
              with:
                  name: spec 2019-09 test results
                  path: test-result-spec2019-09.json
            - uses: dorny/test-reporter@v1.6.0
              with:
                  fail-on-error: false
                  name: spec test results # Name of the check run which will be created
                  path: test-result-spec*.json # Path to test results
                  reporter: mocha-json # Format of test results
                  list-suites: "failed"
