name: CI

on:
    push:
        branches: [main, next, workflow]
    pull_request:
        branches: [main]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install yarn (required locally)
              run: npm install --global yarn
            - uses: actions/setup-node@v3
              with:
                  node-version: "21"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile

    run-unit-tests:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run unit tests
              run: yarn test:unit:ci
            - uses: actions/upload-artifact@v4
              with:
                  name: test-results-unit-tests
                  path: test-result-unit.json
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: test-results / unit-tests
                  path: test-result-unit.json
                  reporter: mocha-json

    run-spec-v4-tests:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test spec v4
              run: yarn test:4:ci
            - uses: actions/upload-artifact@v4
              with:
                  name: test-results-spec-4
                  path: test-result-spec4.json
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: test-results / spec-4
                  path: test-result-spec4.json
                  reporter: mocha-json

    run-spec-v6-tests:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test spec v6
              run: yarn test:6:ci
            - uses: actions/upload-artifact@v4
              with:
                  name: test-results-spec-6
                  path: test-result-spec6.json
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: test-results / spec-6
                  path: test-result-spec6.json
                  reporter: mocha-json

    run-spec-v7-tests:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test spec v7
              run: yarn test:7:ci
            - uses: actions/upload-artifact@v4
              with:
                  name: test-results-spec-7
                  path: test-result-spec7.json
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: test-results / spec-7
                  path: test-result-spec7.json
                  reporter: mocha-json

    run-spec-2019-09-tests:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test spec 2019-09
              run: yarn test:2019:ci
            - uses: actions/upload-artifact@v4
              with:
                  name: test-results-spec-2019-09
                  path: test-result-spec2019-09.json
            - uses: dorny/test-reporter@v1.6.0
              with:
                  name: test-results / spec-2019-09
                  path: test-result-spec2019-09.json
                  reporter: mocha-json
